-- Migration: Create word_list_entry and puzzle_result tables + seed bundled word list
-- Requirements: 13.3, 13.11, 13.13

CREATE TABLE IF NOT EXISTS `word_list_entry` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `word` VARCHAR(45) NOT NULL,
  `category` ENUM('name', 'place', 'book', 'theme') NOT NULL,
  `is_custom` BOOLEAN NOT NULL DEFAULT FALSE,
  `added_by` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_word_list_added_by` FOREIGN KEY (`added_by`) REFERENCES `members`(`id`),
  UNIQUE KEY `uq_word_list_word` (`word`),
  INDEX `idx_word_list_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `puzzle_result` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `member_id` INT NOT NULL,
  `puzzle_type` ENUM('word_search', 'daily_word') NOT NULL,
  `puzzle_date` DATE NOT NULL,
  `solved` BOOLEAN NOT NULL DEFAULT FALSE,
  `guesses_used` INT NULL,
  `duration_seconds` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_puzzle_result_member` FOREIGN KEY (`member_id`) REFERENCES `members`(`id`),
  UNIQUE KEY `uq_daily_result` (`member_id`, `puzzle_type`, `puzzle_date`),
  INDEX `idx_puzzle_result_member` (`member_id`, `puzzle_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `word_list_entry` (`word`, `category`) VALUES
  ('JESUS', 'name'),
  ('MOSES', 'name'),
  ('DAVID', 'name'),
  ('AARON', 'name'),
  ('ISAAC', 'name'),
  ('JACOB', 'name'),
  ('CALEB', 'name'),
  ('SARAH', 'name'),
  ('NAOMI', 'name'),
  ('HEROD', 'name'),
  ('JONAH', 'name'),
  ('ELIJAH', 'name'),
  ('JOSEPH', 'name'),
  ('DANIEL', 'name'),
  ('SAMSON', 'name'),
  ('ANDREW', 'name'),
  ('MARTHA', 'name'),
  ('PILATE', 'name'),
  ('ABRAHAM', 'name'),
  ('SOLOMON', 'name'),
  ('EGYPT', 'place'),
  ('JUDAH', 'place'),
  ('SINAI', 'place'),
  ('CANA', 'place'),
  ('ZION', 'place'),
  ('EDEN', 'place'),
  ('CANAAN', 'place'),
  ('BABEL', 'place'),
  ('SODOM', 'place'),
  ('JORDAN', 'place'),
  ('NAZARETH', 'place'),
  ('BETHEL', 'place'),
  ('GALILEE', 'place'),
  ('JERICHO', 'place'),
  ('JAMES', 'book'),
  ('MARK', 'book'),
  ('LUKE', 'book'),
  ('JOHN', 'book'),
  ('ACTS', 'book'),
  ('TITUS', 'book'),
  ('HOSEA', 'book'),
  ('MICAH', 'book'),
  ('NAHUM', 'book'),
  ('EXODUS', 'book'),
  ('PSALMS', 'book'),
  ('AMOS', 'book'),
  ('RUTH', 'book'),
  ('EZRA', 'book'),
  ('JOEL', 'book'),
  ('FAITH', 'theme'),
  ('GRACE', 'theme'),
  ('MERCY', 'theme'),
  ('PEACE', 'theme'),
  ('CROSS', 'theme'),
  ('LIGHT', 'theme'),
  ('BREAD', 'theme'),
  ('MANNA', 'theme'),
  ('ANGEL', 'theme'),
  ('GLORY', 'theme'),
  ('PRAY', 'theme'),
  ('HOPE', 'theme'),
  ('LOVE', 'theme'),
  ('LAMB', 'theme'),
  ('HOLY', 'theme'),
  ('COVENANT', 'theme'),
  ('SALVATION', 'theme'),
  ('BAPTISM', 'theme'),
  ('GOSPEL', 'theme'),
  ('PRAISE', 'theme'),
  ('SPIRIT', 'theme'),
  ('PROPHET', 'theme'),
  ('TEMPLE', 'theme'),
  ('WISDOM', 'theme');
